### ISSUE TITLE
JavaScript logic for prompting user for information

### ISSUE THREAD

**Issue by Mr-MikeRoss** [Mr-MikeRoss/Color-Racer#4]
1) Player 1 entry
2) Player 2 entry

**Comment by jake-magri** [comment]
Button to refresh the page, bringing back up the form.

**Comment by jake-magri** [comment]
We discussed entering user information through a form that presents to the user when the page is opened, sends the information and caches it (localStorage). This will be accomplished through using the bootstrap modal. There is a button to refresh the page and bring the form back up for updates. There should be a backlog to brainstorm more data to get from the user for the form. (currently only a name).

**Comment by jake-magri** [comment]
Form opens on page start and saves names to cache on submit #13 

formResponse function now stores an array of player objects (player 1 and player 2) with name properties to cache. Objects for scalability in case we'd like to add more player data later.

Bootstrap modal form now presents to user on window load. Added error handling to ensure modal removal on submit.

https://getbootstrap.com/docs/5.3/components/buttons/#methods
https://getbootstrap.com/docs/5.3/getting-started/javascript/#css-selectors-in-constructors
